#!/usr/bin/perl

use lib '/home/pim/lib';

use strict;
use icecat_util;
use icecat_client;

use atomsql;
use atomlog;
use Data::Dumper;

use POSIX qw (strftime);

my $from = strftime("%Y-%m-%d", localtime(time-24*60*60*7));

my $wd = strftime("%w", localtime(time-24*60*60));

if(0 && $wd ne '0'){
 # today isn't sunday
 # bye!
 exit;
}

my $fn = $ARGV[0];

if(!$fn){
 print "No filename given";
 exit;
}


my $hash = {
						'ProductsDump'		=> { 'langid' => '1,2',
#																	 'Supplier_ID'	=> '1',
#																		'MinQuality'	=> 'ICECAT',
																		'MinQuality'	=> 'NOBODY',
																		'UpdatedFrom'	=> $from
																 }
						};


my $hash = {
						'ProductsDump'		=> { 'langid' => '1,2',
#																	 'Supplier_ID'	=> '1',
#																		'MinQuality'	=> 'ICECAT',
																		'MinQuality'	=> 'NOBODY',
																		'UpdatedFrom'	=> $from
																 }
						};

my $message = &build_message(&build_request($hash,'icecat','BcW9NgnbMH',time));
# print $message."\n\n";
my $url = "http://data.icecat.biz/xml_server2.cgi";

#print $$message."\n";

my $response = &post_message($$message, $url, 1);

open(FH, ">".$fn);
print FH $response;
close(FH);



